# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  APP_DIR: suite
  APP_URL: http://localhost:5173

tasks:
  default:
    desc: Launch Terminus web app
    deps: [web]

  install:
    desc: Install web app dependencies
    dir: "{{.APP_DIR}}"
    cmds:
      - npm install

  web:
    desc: Open Terminus in browser and start Vite dev server
    dir: "{{.APP_DIR}}"
    cmds:
      - open "{{.APP_URL}}"
      - npm run dev
